docs/contributing/README.md, package-lock.json, package.json, scripts/templates/create-vue-file.sh, src/components/CapacityIndicator/CapacityIndicator.spec.ts, src/components/CapacityIndicator/CapacityIndicator.stories.ts, src/components/CapacityIndicator/CapacityIndicator.vue, src/index.ts
=> Add capacity indicator component

package-lock.json, package.json, src/components/BccButton/BccButton.vue, src/components/BccInput/BccInput.vue
Update tokens package to remove custom border radius
=> Remove custom border radius

src/components/BccButton/BccButton.stories.ts, src/components/BccButton/BccButton.vue
=> Center button text by default

src/components/BccAvatar/BccAvatar.spec.ts, src/components/BccAvatar/BccAvatar.stories.ts, src/components/BccAvatar/BccAvatar.vue, src/index.ts
- Add Avatar component from Event app
- Add tests
=> Add avatar component

.eslintrc.cjs, .github/workflows/test.yml, package.json
- Add linting step to CI
- Set prettier to error level
=> Add linting to CI

src/components/BccCapacityIndicator/BccCapacityIndicator.spec.ts, src/components/BccCapacityIndicator/BccCapacityIndicator.stories.ts, src/components/BccCapacityIndicator/BccCapacityIndicator.vue, src/composables/animatedNumber.ts
=> possible to disable animation on the capacity indicator

.github/workflows/create-version.yml, .github/workflows/tokens/build-tailwind-config.yml, .github/workflows/tokens/create-pr.yml
=> Automatically create PR for token updates

.storybook/preview.cjs, src/storybook.css, tailwind.compile.config.ts
=> Don't include Tailwind preflight reset in production build

.github/workflows/release-dev-version.yml, .github/workflows/release.yml, .storybook/theme.cjs, README.md, css-package/README.md, css-package/package.json, css-package/tailwind.config.ts, css-package/vite.config.ts, package.json, scripts/version.sh, src/documentation/Introduction.mdx, tailwind.compile.config.ts, tailwind.config.ts, vite.config.ts
-   [ ] No review
-   [ ] Small PR
-   [ ] Big PR
-   [x] Refactor
=> Rename to design-library

src/components/BccButton/BccButton.stories.ts, src/components/BccButton/BccButton.vue
This brings it in line with the new design system naming for contexts.
-   [ ] No review
-   [x] Small PR
-   [ ] Big PR
-   [ ] Refactor
=> Rename button color prop to context

src/components/BccBadge/BccBadge.stories.ts, src/components/BccButton/BccButton.stories.ts, src/components/BccPin/BccPin.stories.ts
=> Fix icons not always loading in Storybook

src/components/BccBadge/BccBadge.stories.ts, src/components/BccBadge/BccBadge.vue, src/components/BccPin/BccPin.stories.ts, src/components/BccPin/BccPin.vue
The styling was already removed
=> Remove outdated system options for badge and pin

src/components/BccButton/BccButton.stories.ts, src/components/BccCapacityIndicator/BccCapacityIndicator.stories.ts, src/components/BccInput/BccInput.stories.ts, src/components/BccToggle/BccToggle.stories.ts, src/css/index.css, src/css/typography.css, src/documentation/typography.stories.ts, src/tokens/tailwind/bccForbundetTheme.ts, src/tokens/tailwind/fontSize.ts, src/tokens/tailwind/lineHeight.ts
=> Add typography

src/components/BccAvatar/BccAvatar.stories.ts
Just to make clear how to achieve this, because it's in the design system.
=> Add list example for Avatar

src/components/BccAvatar/BccAvatar.stories.ts, src/components/BccBadge/BccBadge.stories.ts, src/components/BccButton/BccButton.stories.ts, src/components/BccCookieBanner/BccCookieBanner.css, src/components/BccCookieBanner/BccCookieBanner.vue, src/components/BccInput/BccInput.stories.ts, src/components/BccModal/BccModal.css, src/components/BccModal/BccModal.spec.ts, src/components/BccModal/BccModal.stories.ts, src/components/BccModal/BccModal.vue, src/components/BccModal/__snapshots__/BccModal.spec.ts.snap, src/components/BccPin/BccPin.stories.ts, src/components/BccToggle/BccToggle.stories.ts, src/css/index.css, src/index.ts, src/tokens/tailwind/bccForbundetTheme.ts
Adds a modal component.
Closes #21
=> Add modal component

src/components/BccModal/BccModal.css, src/components/BccModal/BccModal.stories.ts, src/components/BccModal/BccModal.vue, src/components/BccModal/__snapshots__/BccModal.spec.ts.snap
- Fixes the modal overlay where absolutely positioned elements where on top of it.
- Updates title padding & font based on latest design
- Make title prop optional
=> Fix modal overlay & make title optional

src/components/BccInput/BccInput.css, src/components/BccInput/BccInput.stories.ts, src/components/BccInput/BccInput.vue, src/components/BccInput/__snapshots__/BccInput.spec.ts.snap, src/css/typography.css, src/hooks/use-id.ts
- Add large size option to input
- Give input random id
- Do not wrap input in label
- Use CSS class for wrapper
- Add optional icon to input
- Fix caption typography style
Fixes #129
=> Add icon to input

src/components/BccCheckbox/BccCheckbox.stories.ts, src/tokens/plugin/tailwindPlugin.ts, tailwind.config.ts
So consumers of the library don't need to install it as a dependency
Closes #128
=> Import Tailwind Forms plugin in our plugin

.github/workflows/deploy-storybook-dev.yml, .github/workflows/deploy-storybook-production.yml
=> Create dev Storybook site

src/components/BccAlert/BccAlert.css, src/components/BccAlert/BccAlert.spec.ts, src/components/BccAlert/BccAlert.stories.ts, src/components/BccAlert/BccAlert.vue, src/components/BccAlert/__snapshots__/BccAlert.spec.ts.snap, src/components/BccModal/BccModal.spec.ts, src/css/index.css, src/index.ts
=> Create alert component

src/components/BccCapacityIndicator/BccCapacityIndicator.vue, src/components/BccCheckbox/BccCheckbox.vue, src/components/BccInput/BccInput.css, src/components/BccInput/BccInput.stories.ts, src/components/BccInput/BccInput.vue, src/components/BccRadio/BccRadio.vue, src/components/BccSelect/BccSelect.css, src/components/BccSelect/BccSelect.spec.ts, src/components/BccSelect/BccSelect.stories.ts, src/components/BccSelect/BccSelect.vue, src/components/BccSelect/__snapshots__/BccSelect.spec.ts.snap, src/composables/attrsWithoutStyles.ts, src/css/index.css, src/index.ts, vitest.config.ts
=> Create select component mirroring/using input styles

.github/workflows/deploy-storybook-production.yml, tsconfig.compile.json
The new infra setup meant a new production Storybook on https://design-library.developer.bcc.no.
Fixes #140.
=> Update production Storybook deploy to new app

src/components/BccFormLabel/BccFormLabel.css, src/components/BccFormLabel/BccFormLabel.spec.ts, src/components/BccFormLabel/BccFormLabel.stories.ts, src/components/BccFormLabel/BccFormLabel.vue, src/components/BccFormLabel/__snapshots__/BccFormLabel.spec.ts.snap, src/components/BccInput/BccInput.css, src/components/BccInput/BccInput.vue, src/components/BccInput/__snapshots__/BccInput.spec.ts.snap, src/components/BccSelect/BccSelect.spec.ts, src/components/BccSelect/BccSelect.vue, src/components/BccSelect/__snapshots__/BccSelect.spec.ts.snap, src/css/index.css, src/index.ts
Moves the label to a standalone component to be used with other form elements.
=> Create form label component

src/components/BccButton/BccButton.css, src/components/BccButton/BccButton.stories.ts
=> Make icon only button square by default

src/components/BccCheckbox/BccCheckbox.vue, src/components/BccCheckbox/__snapshots__/BccCheckbox.spec.ts.snap, src/components/BccRadio/BccRadio.spec.ts, src/components/BccRadio/BccRadio.stories.ts, src/components/BccRadio/BccRadio.vue, src/components/BccRadio/__snapshots__/BccRadio.spec.ts.snap
- Don't render a label element if there is no label
- Fix v-model not working for radio input
=> Fix v-model not working for radio input

src/components/BccTable/BccTable.vue
The items were copied to a non-reactive property making it not possible to update the items later without triggering a new render of the table.
=> Fix table reactivity issue

src/components/BccAlert/BccAlert.vue, src/components/BccButton/BccButton.vue
Slight readability and performance improvment.
Especially on micro components it helps reducing the amount of conditions being checked, at a component level the difference isn't noticable but once you add such a component to table displaying a 1000 rows then it actually starts having an impact.
=> Change to static lookups instead of multiple ifs

README.md, tailwind.config.ts
Still pointed to the old location.
=> Update Storybook link in readme
